/// orgin pub package: https://pub.dev/packages/cloudbase_database
/// author: https://cloudbase.net/ & lirongcong.bennett@gmail.com

class ErrCode {
  static const String UNKNOWN_ERROR = 'UNKNOWN_ERROR';

  static const String SDK_DATABASE_REALTIME_LISTENER_INIT_WATCH_FAIL =
      'SDK_DATABASE_REALTIME_LISTENER_INIT_WATCH_FAIL';

  static const String SDK_DATABASE_REALTIME_LISTENER_RECONNECT_WATCH_FAIL =
      'SDK_DATABASE_REALTIME_LISTENER_RECONNECT_WATCH_FAIL';

  static const String SDK_DATABASE_REALTIME_LISTENER_REBUILD_WATCH_FAIL =
      'SDK_DATABASE_REALTIME_LISTENER_REBUILD_WATCH_FAIL';

  static const String SDK_DATABASE_REALTIME_LISTENER_CLOSE_WATCH_FAIL =
      'SDK_DATABASE_REALTIME_LISTENER_CLOSE_WATCH_FAIL';

  static const String SDK_DATABASE_REALTIME_LISTENER_SERVER_ERROR_MSG =
      'SDK_DATABASE_REALTIME_LISTENER_SERVER_ERROR_MSG';

  static const String
      SDK_DATABASE_REALTIME_LISTENER_RECEIVE_INVALID_SERVER_DATA =
      'SDK_DATABASE_REALTIME_LISTENER_RECEIVE_INVALID_SERVER_DATA';

  static const String
      SDK_DATABASE_REALTIME_LISTENER_WEBSOCKET_CONNECTION_ERROR =
      'SDK_DATABASE_REALTIME_LISTENER_WEBSOCKET_CONNECTION_ERROR';

  static const String
      SDK_DATABASE_REALTIME_LISTENER_WEBSOCKET_CONNECTION_CLOSED =
      'SDK_DATABASE_REALTIME_LISTENER_WEBSOCKET_CONNECTION_CLOSED';

  static const String SDK_DATABASE_REALTIME_LISTENER_CHECK_LAST_FAIL =
      'SDK_DATABASE_REALTIME_LISTENER_CHECK_LAST_FAIL';

  static const String SDK_DATABASE_REALTIME_LISTENER_UNEXPECTED_FATAL_ERROR =
      'SDK_DATABASE_REALTIME_LISTENER_UNEXPECTED_FATAL_ERROR';
}
